# Generated by Django 5.2.6 on 2026-02-11 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0003_horariobloque"),
        ("index", "0008_delete_contacto_delete_newspost_delete_reserva"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título de la publicación",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Contenido completo de la publicación",
                        verbose_name="Contenido",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen principal de la publicación",
                        null=True,
                        upload_to="blog/",
                        verbose_name="Imagen destacada",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Si está publicado, se muestra en la landing page",
                        verbose_name="Publicado",
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de publicación",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Publicación",
                "verbose_name_plural": "Publicaciones",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensaje")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nuevo"),
                            ("read", "Leído"),
                            ("replied", "Respondido"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas privadas del administrador (no visibles para el cliente)",
                        verbose_name="Notas internas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de recepción"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de contacto",
                "verbose_name_plural": "Mensajes de contacto",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ej: Clases de Pilates, Kinesiología",
                        max_length=200,
                        verbose_name="Nombre del servicio",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción completa del servicio",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Precio en pesos chilenos (sin decimales)",
                        max_digits=10,
                        verbose_name="Precio (CLP)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Imagen representativa del servicio",
                        upload_to="services/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si está activo, se muestra en la landing page",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Orden de visualización (menor número aparece primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
                "ordering": ["order", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="reservaclase",
            name="clase",
        ),
        migrations.DeleteModel(
            name="Contacto",
        ),
        migrations.DeleteModel(
            name="HorarioBloque",
        ),
        migrations.RemoveField(
            model_name="perfilusuario",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="reservaclase",
            name="cliente",
        ),
        migrations.DeleteModel(
            name="ClasePilates",
        ),
        migrations.DeleteModel(
            name="PerfilUsuario",
        ),
        migrations.DeleteModel(
            name="ReservaClase",
        ),
    ]
