# Generated by Django 5.2.6 on 2026-02-19 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0004_blogpost_contactmessage_service_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre y apellido del instructor",
                        max_length=100,
                        verbose_name="Nombre completo",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Foto profesional del instructor",
                        upload_to="instructors/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "specialties",
                    models.CharField(
                        help_text="Ej: Mat & Reformer - Instructora Principal",
                        max_length=200,
                        verbose_name="Especialidades",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="Descripción breve del instructor (experiencia, enfoque)",
                        verbose_name="Biografía",
                    ),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True,
                        help_text="Lista de certificaciones y formación (opcional)",
                        verbose_name="Certificaciones",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Orden de visualización (menor número aparece primero)",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si está activo, se muestra en la landing page",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Instructor",
                "verbose_name_plural": "Instructores",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                help_text="Imagen principal de la publicación (obligatoria)",
                upload_to="blog/",
                verbose_name="Imagen destacada",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="published_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Se establece automáticamente al crear/editar",
                verbose_name="Fecha de publicación",
            ),
        ),
    ]
