# Generated by Django 5.2.6 on 2026-03-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0005_instructor_alter_blogpost_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-published_date", "-created_at"],
                "verbose_name": "Post del blog",
                "verbose_name_plural": "Posts del blog",
            },
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="service",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(verbose_name="Contenido"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(upload_to="blog/", verbose_name="Imagen"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Publicado"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="published_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de publicación"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(upload_to="services/", verbose_name="Imagen"),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nombre del servicio"),
        ),
        migrations.AlterField(
            model_name="service",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Orden de visualización"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Precio (CLP)"
            ),
        ),
    ]
