# Generated by Django 5.2.6 on 2026-02-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_alter_user_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rol",
            field=models.CharField(
                choices=[("administrador", "Administrador")],
                default="administrador",
                help_text="Rol del usuario en el sistema",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
