# Generated by Django 5.2.6 on 2025-09-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_contacto_comentario_contacto_estado_mensaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('tag', models.CharField(choices=[('Consejos', 'Consejo'), ('Eventos', 'Evento'), ('Promos', 'Promo'), ('MK', 'MK · Historia')], default='Consejos', max_length=16)),
                ('excerpt', models.TextField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-published_at'],
            },
        ),
    ]
