# Generated by Django 5.2.6 on 2026-02-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0007_newspost"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contacto",
        ),
        migrations.DeleteModel(
            name="NewsPost",
        ),
        migrations.DeleteModel(
            name="Reserva",
        ),
    ]
